### ISSUE TITLE
MISCOUNT of Data: COSPONSOR (Livingstone) 

### ISSUE THREAD

**Issue by harmonywho** [aholachek/legislator-scorecard#32]
Apologies for being absent on this proj today; I will get back to it. I was showing some ppl at my ACLU meeting, and we found a "glitch" an error or miscount or something on Jay Livingstone's cosponsor page: 
He's listed as cosponsoring 11 / 16, 
![image](https://cloud.githubusercontent.com/assets/26801934/24635750/8cd07326-18a3-11e7-98d4-e478538f2a7f.png)
But the count on his page shows he's only missing 2. 
... But then when you count, **there are only 13 bills being listed on his page:** 
![image](https://cloud.githubusercontent.com/assets/26801934/24635820/fca885d0-18a3-11e7-9bd1-6d4e2bd9d370.png)

![image](https://cloud.githubusercontent.com/assets/26801934/24635715/318ae622-18a3-11e7-918e-2cd78853a9f8.png)
I"ll do some checking of the doc / data source later, if I can, but flagging for you. And me. 
(lmk which is the tab you're pulling from when you have a chance) 

I haven't checked others yet; leaving boston/board meeting for now.

**Comment by harmonywho** [comment]
[Just checked GARLICK's page; ](https://progressive-mass.firebaseapp.com/my-legislators/%20MA%2002492)13 only there too: 
![image](https://cloud.githubusercontent.com/assets/26801934/24639882/d4952ae0-18c0-11e7-85e8-b3453a28a147.png)

**Comment by aholachek** [comment]
I just wrote you an email about it. Basically it seems that now that I am parsing the cosponsorship spreadsheet into a house and a senate version, there are 3 missing rows for house bills that are not there anymore, which throws everything off. This is probably a result of my misunderstanding of how to display the house vs senate versions of bills, but also maybe an argument to keep 2 separate cosponsorship spreadsheets, one for each chamber, instead of one big spreadsheet.

**Comment by aholachek** [comment]
fixed based on our convo yesterday
